### PR TITLE
Add support for embedded Crystal code snippet highlighting.

### PR DESCRIPTION
**Pull request by keplersj**
I did compile and test it locally, however I didn't commit the newly compiled JSON.

### CODE REVIEW

**Comment by burodepeper** [comment]
Thanks for the PR.

Is there any particular reason why you've commented but not included `{ pattern:'ecr', include:'source.crystal', contentName:'text.html.ecr'}`?

**Comment by burodepeper** [comment]
Oh wait, that's probably because `erb` doesn't work either. Just noticed that Crystal is related to Ruby.

**Comment by keplersj** [comment]
Yeah, I saw that ERB was commented out and wasn't sure why so added ECR as a comment alongside it. ECR and ERB are very similar, much like Crystal and Ruby.

**Comment by burodepeper** [comment]
Okay, thanks. ERB is commented out, because embedded languages don't work yet. Same goes for PHP for instance. I've merged the PR, and will release an update it shortly.

**Pull request merged**
