### PR TITLE
allow more generic Rmarkdown (.Rmd) blocks 

### PR DESCRIPTION
**Pull request by pimentel**
This is the `language-markdown` version of the pull request here: https://github.com/atom/language-gfm/pull/130

---

Currently only code blocks that start with `r ` are supported for Rmd (Rmarkdown). In practice, you commonly have a block that start like this: 

`{r}`

or

`{r, cache=TRUE}`

the possibility of no or many arguments.

This pull request allows these types of expressions. Unfortunately, it doesn't intelligently insert the language type when `engine=` is set to anything other than `R` (you could set it to things such as `bash`, `python`, etc.). In this case, it would simply set the language to R.

### CODE REVIEW

**Comment by burodepeper** [comment]
Thanks for the PR!

I am quite unfamiliar with this. Would you mind adding some examples of what this would look code-wise? In the reference from language-gfm, I see something like this:  `{r,eval=TRUE,cache=FALSE}`

This package already adds support for special-attributes in fenced-code-blocks, so I'd like to make sure that these parameters are parsed correctly and don't interfere with what is already there. I am not sure if adding the parameters as part of the fenced-code pattern is the best way to solve this. Feels a bit like a "bandaid".

Would you mind adding specs to make sure things are parsed correctly?

**Comment by pimentel** [comment]
Thanks for the quick response!

Rmarkdown is a Markdown variant that allows you to include chunks that will actually get interpreted by [R](https://cran.r-project.org/) and the results will get output into a document. As a result, the block descriptions has several attributes which control how the block is executed. You can see many examples [here] (http://rmarkdown.rstudio.com/authoring_rcodechunks.html)

I'll be honest -- I don't grok most of the code in this package (I took the easiest path) so there might be a better way to do this. Anyway, my goal with adding the regular expression is simply to ensure that the code in the fenced-block still gets tagged correctly as `R` when the expression looks more like a Rmarkdown expression rather than a normal Markdown expression.

I can add some specs soon.


Thanks

**Comment by burodepeper** [comment]
Merci again!

I'm wholly unfamiliar with R, but I've seen it come by, so there's probably no harm in supporting it. The markup with the curly-braces is particularly used by Rmarkdown, isn't it? I think it's best to create some custom grammar for it then. Would be nice to have the arguments tokenized as well.

Let me know if you want to have a jab at it, otherwise I'll put it on my list. The examples you've provided should suffice for me at least to create the grammar that's needed, but it could take a little while until I've implemented it. I think leaving the normal implementation of the R fenced-code-block as is the best for now.

**Comment by pimentel** [comment]
>The markup with the curly-braces is particularly used by Rmarkdown, isn't it? 

Yes. Although, I don't think any of the arguments affect the grammar with the exception of `engine=someOtherLanguage`, so in this sense, it would be helpful as you suggest to tokenize the arguments.

After taking another quick peek, it seems that adding its own grammar would result in a few files here:

https://github.com/burodepeper/language-markdown/tree/master/grammars/repositories/flavors

?

I have very little experience with this, so maybe it might be best if you added to your list for now. I can probably take a serious look at this in about 2 weeks, so when my schedule clears up, if you haven't gotten to it already I will take a stab at it.

**Comment by burodepeper** [comment]
I'll have a better look at the documentation tomorrow, and I'll get back to you.

**Comment by burodepeper** [comment]
Hi @pimentel,

I've taken a closer look, and I indeed think it is best to implement this as a distinct _R Markdown flavor_ instead of modifying the general purpose R fenced-code-block. I'll get started on it in a `dev-rmarkdown` branch (off of `dev`) somewhere next week, and I'll ping you (and close this PR) when there's something worthwhile to look at. The `engine=...` element might need some puzzling, but all in all it shouldn't be that difficult to add this as a flavor. Also, tokenizing the attributes allows for better syntax-highlighting. See [this for example](https://github.com/burodepeper/language-markdown/issues/37#issuecomment-156360865), even though at that time the grammar was still incomplete.

**Comment by burodepeper** [comment]
I'm closing this PR in favor of #82. Feel free to pitch in when you have time.

**Pull request closed without merging**
