### PR TITLE
Update lists

### PR DESCRIPTION
**Pull request by burodepeper**
- [x] Add numbered task-lists
- [x] Allow regular task-lists to start with a `+` or `*`
- [x] Check if in-/outdenting of task-lists works with new options
- [x] Check if automatically creating new task-list-items works with new options
- [x] Allow capital X to mark a task as complete

### CODE REVIEW

**Comment by ryan-p-randall** [comment]
Would it be possible to also allow regular task-lists to start with a `-`?  

As others have said, I profoundly appreciate all the work you're doing with this!

**Comment by burodepeper** [comment]
Hi @ryan-p-randall,

First of all, thank you and you're welcome! Secondly, task-lists in the current release actually only work with dashes, so if they don't for you, there is probably something else going wrong. Could you make sure you have the correct grammar selected (it should, because this package should disabled `language-gfm`, but just to be sure) and then post a screenshot with both a normal and a completed task in it?

```markdown
- [ ] task
- [x] completed task
```

**Comment by ryan-p-randall** [comment]
Hi @burodepeper, 

The grammar for this file says "Markdown," so I think it's correct. The settings show `language-gfm` as disabled. 

Here's two examples that show how I use numbered and unnumbered task lists. They're rendered in your Minimal-Syntax-Dark theme and then in Paraíso Dark, the main one I use.  

Maybe I'm just misunderstanding the theme colors? Should the `[ ]` task boxes always show as a different color than headings and text? 

exampleminimaldark
exampleparaisodark

**Comment by burodepeper** [comment]
What I'm seeing in the `minimal-syntax-dark` one is as intended (in the current version). In that theme I've chosen to highlight the punctuation element of the list-item (of whatever type it is). And completed tasks are greyed-out. Because task-list-items aren't recognized yet when they are marked either numerical or with a `+` or `*`, you get some cyan-colored empty labels. What other syntax-themes is concerned, it depends on them if they do anything with the classes that I provide.

This PR that you're replying to will enable those checkboxes for list-items that start with a `+` and `*` too, but I haven't released it yet. It's probably coming out the weekend after next. I don't want to spam users too often with updates. If I hadn't screwed up my current development version of `minimal-syntax-dark` I'd have made you a screenshot to show off what it will look like.

**Comment by ryan-p-randall** [comment]
Great, thank you for clarifying all of this. The greyed-out tasks are a fantastic addition! I entirely understand about other syntax themes.

**Comment by burodepeper** [comment]
I'm working on a rather big thing (see #83) which should make it easier for syntax-themes to implement things. It is actually quite easy to add some custom styling to the syntax-theme you use. Let me know if you're interested, and I'll walk you through adding greyed-out tasks for example.

**Pull request merged**
