### PR TITLE
Add list-items when pressing enter

### PR DESCRIPTION
**Pull request by burodepeper**
- [x] Add an option to disable this functionality via the settings
- [x] Add a thank you note somewhere for @jonmagic
- [x] Check if this doesn't cause issues with embedded code
- [x] ~~Check if the interaction feels natural in nested lists~~

### CODE REVIEW

**Comment by jonmagic** [comment]
This is really great, I learned a ton about tokens in Atom reading through this PR. Super excited for this feature also and your implementation seems way more robust and extendable than my hacks :sparkles: Thank you for reaching out :metal:

**Comment by burodepeper** [comment]
Thanks for looking at it! I'll ping you when it's live. I want to sort the embedded code bit out before I merge it. Quick question, do you think people actually use nested lists in Markdown such as
```markdown
1. 1. Apples
    2. Bananas
    3. Chocolate
```
? I'm doubting how much time I should spent on getting that indentation sorted out when pressing enter after 'apples'.

**Comment by jonmagic** [comment]
I've seen a lot of lists like this at GitHub:

```
- [ ] project name
  - [ ] project sub task 1
  - [ ] project sub task 2
- [ ] other project name
  - [ ] other project sub task 1
  - [ ] other project sub task 2
```

But I don't think that kind of thing needs to work in a v1 of the feature.

**Comment by burodepeper** [comment]
Oh, I've already got that one sorted out. ; )
But you are probably right. Besides the embedded-code issue, it's good enough for a v1.
Merci.

**Comment by jonmagic** [comment]
> Oh, I've already got that one sorted out. ; )

Oh gotchya, I guess I didn't understand the example completely :) Cheers :beers:

**Comment by burodepeper** [comment]
New version is published; let me know what you think! But have a nice weekend first ; )

**Pull request merged**
