### PR TITLE
Added har extension for syntax highlighting

### PR DESCRIPTION
**Pull request by ntotten**
Adds support for `har` syntax highlighting using json.

See: http://www.softwareishard.com/blog/har-12-spec/

### CODE REVIEW

**Comment by burodepeper** [comment]
Thanks! If you want to take the "official" credit, would you mind submitting the PR against the `dev` branch? Otherwise I'll add it manually.

**Comment by burodepeper** [comment]
I'm impatient, so I added it myself. ;) Also there was a typo in your PR, so closing this.

**Comment by ntotten** [comment]
Thanks! It was on my todo, but been a busy week. :)

**Comment by burodepeper** [comment]
Update is published!

**Pull request closed without merging**
