### PR TITLE
Add R Markdown flavor

### PR DESCRIPTION
**Pull request by burodepeper**
- [ ] Implement grammar
  - [ ] Parse and use `engine` argument _before_ evaluating the other attributes
  - [x] Improve parsing of attributes to limit values for specific keys (ie, `fig.align` can be just a few things)
  - [ ] Implement 'complicated' attributes, such as `dev.args` (low priority)
  - [x] What characters can the `label` be made up off?
  - [x] Invalidate attributes when not correctly separated by commas
- [ ] Write specs, a lot of specs
- [ ] Add examples to EXAMPLES.md
- ~~Replicate and fix the `print()` issue~~
- [ ] Merge with `dev` and move incomplete tasks to a new PR

### CODE REVIEW

**Comment by pimentel** [comment]
@burodepeper this is looking very nice! I will be happy to test it in the coming days. thanks for doing this.

**Comment by burodepeper** [comment]
You're welcome! Here's a little screenshot of the current status:

schermafbeelding 2016-01-19 om 23 45 21

Quick question that I haven't been able to find a satisfying answer to: the comma in the argument, is that just an arbitrary separator, or does it actually have a function. I have seen examples without a comma, I have seen example with a single comma, with multiple commas. Not sure what to make of it.

**Comment by pimentel** [comment]
that is a good question. it's not very clear from the documentation, is it? when I get home from work I will check. I will run all of your examples (and add of more tests accordingly) depending on what I find

**Comment by burodepeper** [comment]
Thanks! I plan on adding specific attributes (instead of generic ones as
they are now) as well. There are (luckily) not that many. Do you have any
idea how many engines R supports? I've only seen about a handful in
examples.

**Comment by pimentel** [comment]
Regarding your engines question, there are actually more than I thought were: http://yihui.name/knitr/demo/engines/

In practice, I have only seen a few used: python, bash, Rcpp

Regarding the comma question, it is not optional (it is required) when separating arguments. For example, the following does not compile:

```{r another_block cache=TRUE echo=TRUE}
x <- rnorm(30)
sum(x)
```

It is important to note that the second argument (`another_block` in the example above) is optional and is a label for the block. The proper form of the previous block is the following:

```{r another_block cache=TRUE, echo=TRUE}
x <- rnorm(30)
sum(x)
```

Though, the space between the comma is optional

Back to the comma, from many examples that I have seen, I don't think that using it in between `r` and the arguments is technically proper Rmarkdown, though I will say that it definitely works and definitely compiles. From what I can tell, the following 2 are equivalent:

```{r, cache=TRUE}
rnorm(10)
```

```{r cache=TRUE}
rnorm(10)
```

Does that answer your questions? Let me know if it doesn't.

**Comment by burodepeper** [comment]
Thanks, I can work with that!

**Comment by burodepeper** [comment]
It is coming along nicely. I've updated the todo-list in OP. The current version is already quite useful/usable (see screenshot below), but a few key elements are still missing (required commas and using the specified engine).

schermafbeelding 2016-01-20 om 11 06 24

**Comment by burodepeper** [comment]
@pimentel From the docs: "Knitr will evaluate the chunk in the named language, e.g. engine = 'python'. Run names(knitr::knit_engines$get()) to see supported languages." Could you do that for me and post the output here?

**Comment by pimentel** [comment]
@burodepeper sorry I've been out of touch, I've been traveling. I'm going to try out the development version later today. It looks awesome!

Anyway, here is what you asked for:

```r
> names(knitr::knit_engines$get())
 [1] "awk"       "bash"      "coffee"    "gawk"      "groovy"    "haskell"
 [7] "lein"      "mysql"     "node"      "perl"      "psql"      "python"
[13] "Rscript"   "ruby"      "sas"       "scala"     "sed"       "sh"
[19] "stata"     "zsh"       "highlight" "Rcpp"      "tikz"      "dot"
[25] "c"         "fortran"   "asy"       "cat"       "asis"      "stan"
```

**Comment by burodepeper** [comment]
Merci beaucoup! And a six hour response, while travelling, is still a pretty good response time ; )

**Comment by pimentel** [comment]
@burodepeper I've been using this and it works pretty great -- thanks! I've noticed 1 issue though. The syntax highlighting seems to be off when you have the following:

```{r}
print('hello world')
```

I think it never leaves the decorator mode

**Comment by burodepeper** [comment]
@pimentel Thanks for testing! I've got some other things I want to implement, and I'll have a look at that `print('hello world')` thing. I hope to have the update out next weekend.

**Comment by burodepeper** [comment]
@pimentel Could you post a screenshot of what goes wrong with your `print('hello world')` example? I can't seem to replicate it.

**Comment by pimentel** [comment]
@burodepeper sorry for the delay. here is an example. I'm wondering if it's just an issue with the theme that I am using:

screen shot 2016-02-15 at 5 34 22 pm

**Comment by pimentel** [comment]
@burodepeper I'm an idiot -- I wasn't in development mode. sorry about that (it looks good!)

**Comment by burodepeper** [comment]
Hahaha, don't worry about it! ; ) Thanks for your help so far!
I'll be publishing an incomplete implementation shortly, and I'll work on some of the more advanced stuff later. Do you mind if I include you there if I need some feedback?

**Comment by pimentel** [comment]
@burodepeper sounds good! thanks again for all the hard work. lots of people will appreciate this!

**Comment by burodepeper** [comment]
Cool! Let me know if you have any other ideas for improvements.

**Comment by guillaumechaumet** [comment]
Hi guys,
I reopen the case with this example
`
{r 'myfig', echo=FALSE, results='asis',fig.cap='\\label{fig:suivi} figure title',message=FALSE,warning=FALSE}

ggplot(data=patients_Ext,aes(x=followup)) + geom_histogram(bins=40) + theme_bw() + xlab('Duration') + ylab('Count')

`

At the end of figure title', syntax detect beginning of a string, thus the following code is coloured as a string until a new quotation mark come. Perhaps, it's produced by the bracket detection \\label{fig:suivi}. Any idea?

**Comment by burodepeper** [comment]
Thanks for reporting. I will delve into it when I have a bit more free time.

**Pull request merged**
