### PR TITLE
support language jsx

### PR DESCRIPTION
**Pull request by afc163**
<pre>
```jsx
```
</pre>

### CODE REVIEW

**Comment by burodepeper** [comment]
Hi @afc163,
First of all, thanks for the PR. Unfortunately, this package's grammar is compiled, so adding this has to take a little detour, but it will show you some other niceties along the way.

When you open `language-markdown` in Atom in dev-mode, an extra command is added which allows you to compile the grammar from all the various bits and pieces. One of those bits are the fenced code blocks in `/grammars/fixtures/fenced-code.cson` or https://github.com/burodepeper/language-markdown/blob/master/grammars/fixtures/fenced-code.cson
You can add `jsx` to that list, and recompile the main grammar (see the keymaps for your platform specific keybinding), and that should do the trick.

I'd be happy to do any of the above myself, but I'd like to know your experience with it. I realize now that it would be most useful to add some sort of 'how stuff works' section to the readme ; )

**Comment by afc163** [comment]
OK, I will try it later, thx for reply.

**Comment by burodepeper** [comment]
You're welcome. Looking forward to your contribution.

**Comment by burodepeper** [comment]
I've added some extra information on how things work to https://github.com/burodepeper/language-markdown/blob/dev/README.md
Let me know if you need any help.

**Pull request closed without merging**
