### PR TITLE
Proposal for test framework.

### PR DESCRIPTION
**Pull request by leipert**
@burodepeper The tests are now written in a yaml format.

I converted three tests to the new format.

Do you like it as well?

### CODE REVIEW

**Comment by burodepeper** [comment]
Looks perfectly fine at a first glance with sleepy eyes. You'll have my definite answer in a few hours!

**Comment by burodepeper** [comment]
I _like it_, but I have some doubts as well.
First of all, kudos for working towards a better workflow.
There are a few points though that we need to iron out.

### Issues

**What is the exact thing you want to improve/change?**
Or posed differently: why do you want to do it this way? This is not meant as a critique, but more to solidify the reasoning to differ from the standardized approach to testing (in Atom).

**Specs have moved from an executable to a data file**
I needed to give this some thought, but my main issue is that you've moved the specs from a file that is executed to a file that is interpreted. At first, that seemed logical to me as well; rules should be written down in a simple data format. I agree that the way specs are written is rather verbose (although you can copy and paste them together pretty easy). But this change means _more limitations_ and thus less flexibility.

For instance, I have a very thorough approach to my work, and while a space in the wrong scope wouldn't be a real problem, it can really bug me. So when I'm working on the specs, I often put some extra temporary logic in my spec file, to log a dump of a bunch of tokens for example. Of course, exceptions can be made for everything (you're getting a bonus point for the 'todo'-flag later on), but the current situation gives me a shitload of control over what I am doing.

To illustrate the limitations: the new approach is limited to testing for `toEqual()`, while the Jasmine suite offers a lot of other things. True, in a language pack `toEqual()` is probably enough, but still...

**Premature conclusion**
At this point I think it is a really useful tool for scaffolding a conventional `-spec.coffee` file (and taking the 'normal' approach from there), but not as a structural replacement. It could be a really popular tool on its own.

#### Other thingies

Both these points come from a (code) design perspective, so they are definitely not major hurdles and can be put on hold for the time being.

**data structure**
I think the structuring of the data could be improved. It is sunday morning, and I haven't had a potent enough dose of caffeine yet, so you'll have to forgive me for not providing an alternative on the spot.

**yaml vs cson**
My personal preference still goes to cson. That is part _new-things-are-scary_, part _my-theme-isnt-optimized-for-yaml-yet_, and part because of the first point, which hinders my mental parsing of the data.

#### Bonus points

A bonus point for the todo flag btw. No, make it two. Stuff like that could make this whole thing move from _changing_ things, to _improving_ things.

---

Let's set a date and time to Skype about these things.

**Comment by tpoisot** [comment]
I like it. It makes a lot of sense to write the test code automatically, and have a file that only describes the expected behavior. Maybe people @atom can comment too?

**Comment by burodepeper** [comment]
It has its limitations, but it would be a good start to describe the spec for language grammar in a format that is separated from the Jasmine logic.

**Comment by tpoisot** [comment]
It can be good for development, but would have to be changed for the releases, probably. In any case, I think using `cson` instead of `yaml` would make it more Atom-like.

**Comment by leipert** [comment]
Yeah, funny. You came to almost the same conclusion in the cson, @burodepeper .
There is only one flaw in version `6b`:

```coffeescript
input:
  0: '# Heading'
output:
  0: 'text.md heading.md heading-1.md': # <-- Here the scopes are the key
    0: '#': 'punctuation.md' # <-- Here the scope is the value
    1: ' ' # <-- Here the value is the value
    2: 'Heading' 
```

So in my opionion, this would be better:
```coffeescript
input:
  0: '# Heading'
output:
  0: 'text.md heading.md heading-1.md':
    0: ''punctuation.md': '#'
    1: ' '
    2: 'Heading' 
```

**Comment by burodepeper** [comment]
Yeah, I noticed the similarities as well. I thought the exampled you showed me from that other project was a nice way to separate `input` from `output`. And I added the numbering for clarity. For the rest, yeah, from how it evolved, you can clearly see I came to pretty much the same conclusion : )

About the order of items.
From a design point of view, from reading it as a user, I think `nr > value > scopes` is most logical. That means that the second item on a line doesn't mean the same, but I think it can be easily deduced whether that item has children or not.

**Comment by leipert** [comment]
Well I do not think, it is to hard to implement, but just like this more:

```coffeescript
output:
  0: '<line1scope>':
    0: '<token1scope>': 'token1' # linescope + tokenscope = 
    1: 'token2' # no additional tokenscope to the line
  1: '<line2scope>':
    0: 'token1'
```
Maybe this would be better:
```coffeescript
output: [
  '<line1scope>': [
    '<token1scope>': 'token1' # linescope + tokenscope = 
    'token2' # no additional tokenscope to the line
  ]
  '<line2scope>': ['token1']
]
```

**Comment by burodepeper** [comment]
It is not that big of a deal, but **please can I at least have my numbers!!** : )

**Comment by leipert** [comment]
Okay. You will get them

**Comment by leipert** [comment]
And it even will be `6b`, as i understand the appeal of the readability over the consistency.

**Comment by burodepeper** [comment]
Looking forward to an update, when you have the time for it.
Btw `6a` and `6b` are the same idea, but from different content.

**Comment by leipert** [comment]
About multiline input syntax. I actually would prefer multiline strings, as they are more easily copyable than the array syntax

```coffeescript
input: """
****
# FOO
****
"""
```

**Comment by burodepeper** [comment]
The numbers in cson aren't an array btw. They are keys in an object. Especially in the output, you would want to omit certain lines, and especially then it would be a big help to be able to map them directly to the number of the line on the input.

**Comment by burodepeper** [comment]
And I can also chime in on the input side. Just tell me in what needs to happen and where in your code.

**Comment by leipert** [comment]
Can we agree on v7, that I just pushed?
For an empty line, I would simply do:

```coffeescript
input: """
***

***
"""
output:
  0: '***': 'text.md hr.md'
  1: null
  2: '***': 'text.md hr.md'
```

**Comment by burodepeper** [comment]
Give me an evening to think about it. I've got some other things nagging at me right now. I'll also dig up a more complex example to see if we've missed something.

**Comment by leipert** [comment]
Regarding your debugging "problems". An easy solutions would just be:
Add a debug flag to a test (just like the todo flag) and the output would be logged to the console:

```coffeescript
name: 'A test that will be debugged'
debug: true
input: '# Heading'
output:
  0: 'text.md heading.md heading-1.md': # line 0
    0: '#': 'punctuation.md'            # l0:token0
    1: ' '                              # l0:t1
    2: 'Heading'                        # l0:t2
```

**Comment by burodepeper** [comment]
Good idea. I will take it into account when sketching out my `v8`.

**Comment by burodepeper** [comment]
I've added `v8` as a complete fixture, with a simple and a complex test.

In the complex example you can see that I've intentionally left out most of the output. This is because in this example, I am not interested in those parts (because it was an issue submitted by a user). This is where the numbering of the lines in the input is pretty nifty.

Perhaps the `debug` flag should have different options:
```cson
debug: false # (or omitted, is the default setting)
debug: 'output' # only the lines specified in output
debug: 'full' # all lines in output
```

I've also changed `name` to `comment`. None of these is specified in the Jasmine code, so we could also leave it out and just use normal comments.

Perhaps a `skip` toggle could be handy, but again, just commenting the test does the same thing.

**Comment by leipert** [comment]
I would love name and comment, so that we are able to show better error messages.

Should I port the tests to CSON today?

Regarding v8, I like the approach of not writing all the tokens out. But the problem with that would be:

1. We do not know how many tokens there are in a line
2. We do not know how tokens of the same type are separated.


```coffeescript
name: 'A test that will be debugged'
debug: true
input: '# Heading'
output:
  0: 'text.md heading.md heading-1.md':
    0: '#': 'punctuation.md'
    #1: ' ' 
    #2: 'Heading'
```

**Comment by burodepeper** [comment]
My vote is for `description` (in the sense that `name` is a bit ambiguous), but something like that doesn't really matter at this stage. Comment is unnecessary, because you can just add regular cson comments.

Sure, let's switch to cson. I've been holding back on writing specs : )

Why are those two points an issue? They are not array indices, but keys in an object. So you can just test if a certain keys exists, and then check the output. If a key in output doesn't exist in input, that's an error (something something `undefined`). Am I missing something?

**Comment by leipert** [comment]
The issue is, that we check how much tokens we get for each line. And if you the last indices are commented out (see example above), we do not know how many there are.

Furthermore we do not know if it tokenized correctly or not :+1:

**Comment by burodepeper** [comment]
I still think we are on a different page.
I'm going to try and write out how I would solve this in pseudo code. I've left out a few things to make it more compact.
```coffee
data: [
  {
    input: '# Heading'
    output:
      0: 'text.md heading.md heading-1.md':
        0: '#': 'punctuation.md'
        #1: ' ' 
        #2: 'Heading'
  }
]

for test in data
  tokens = test.input.tokenizeLines()
  for line, l in test.output
    for token, t in line
      if tokens[l][t] exists
        valueMatches = tokens[l][t].value === token.value
        scopesMatch = tokens[l][t].scopes === token.scopes
        return (valueMatches and scopesMatch)
```
I think we don't have to check how many tokens we get for each line, and we don't have to check if the input is tokenized correctly. We only have to check if the items specified in output exist and match their counterparts in input.

I think my wish to have the line numbers specified in input as well, was because I had this kind of mapping in my mind. You map the output on top of the input. Ignore everything that isn't defined in output, and diff the rest. If the diff equals zero (no differences) the test is successful. If not, the places that differ are displayed to the user as errors.

Am I making sense? Maybe we should try to code this together somewhere tomorrow?

**Comment by burodepeper** [comment]
I've tried writing some of the specs in the v8 format, and to be honest: it is nothing like a piece of cake. The same test in Jasmine are verbose, but you don't have to _think_ while writing them. I don't yaml would make it easier. Perhaps we should think of a new file format, with an accompanying syntax highlighting...

**Comment by burodepeper** [comment]
I've been thinking that perhaps a form of css could be used.

For example:
```cson
it: 'tokenizes ATX headings'
tests: [
  {
    input: '# foo *bar* \\*baz\\*'
    output:
      0: 'text.md heading.md heading-1.md':
        0: '#': 'punctuation.md'
        1: ' '
        2: 'foo '
        3: 'emphasis.md':
          0: '*': 'punctuation.md'
          1: 'bar'
          2: '*': 'punctuation.md'
        4: ' '
        5: '\\*': 'punctuation.md'
        6: 'baz'
        7: '\\*': 'punctuation.md'
  }
]
```
would become
```css
text.md {
  heading.md {
    heading-1.md {
      punctuation.md {'#'}
      ' '
      'foo '
      emphasis.md {
        punctuation.md {'*'}
        'bar'
        punctuation.md {'*'}
      }
      ' '
      escape.constant.md {'\\*'}
      'baz'
      escape.constant.md {'\\*'}
    }
  }
}
```
and then perhaps make it a little bit more like cson/coffee
```
text.md
  heading.md
    heading-1.md
      punctuation.md '#'
      ' '
      'foo '
      emphasis.md
        punctuation.md '*'
        'bar'
        punctuation.md '*'
      ' '
      escape.constant.md '\\*'
      'baz'
      escape.constant.md '\\*'
```
and then maybe a bit more readable
```
text.md
  heading.md
    heading-1.md
      '#': punctuation.md
      ' '
      'foo '
      emphasis.md
        '*': punctuation.md
        'bar'
        '*': punctuation.md
      ' '
      '\\*': escape.constant.md
      'baz'
      '\\*': escape.constant.md 
```

**Comment by burodepeper** [comment]
Sorry for the flood of messages ; )

I've been playing around with it a bit more, and I think this is what I'd prefer:
```
'# foo *bar* \\*baz\\*' {
  text.md {
    heading.md {
      heading-1.md {
        '#': punctuation.md
        ' '
        'foo '
        emphasis.md {
          '*': punctuation.md
          'bar'
          '*': punctuation.md
        }
      ' '
      '\\*': escape.constant.md
      'baz'
      '\\*': escape.constant.md
      }
    }
  }
}
```
- It stays similar to css (yay for curly braces)
- If a _selector_ is a `string`, then it is _input_
- If a _selector_ is a `classname` (of sorts), then well, it is a _scope_
- The shorthand `string: scope` can be used for the deepest level

**Comment by burodepeper** [comment]
Whipped up a quick grammar pack `.ass` files (Awesome Scope Specs):

schermafbeelding 2015-09-27 om 18 04 41

**Pull request closed without merging**
